name: Windows Cloud PC - Chrome Remote Desktop

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      # 🔊 ATIVAR ÁUDIO
      - name: Enable Audio
        run: |
          Set-Service -Name Audiosrv -StartupType Automatic
          Start-Service Audiosrv

      # 📥 BAIXAR CRD
      - name: Download Chrome Remote Desktop
        run: |
          Invoke-WebRequest https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi -OutFile crd.msi

      # ⚙️ INSTALAR CRD
      - name: Install Chrome Remote Desktop
        run: |
          Start-Process msiexec.exe -ArgumentList "/i crd.msi /quiet /norestart" -Wait

      # 🔐 INICIAR ACESSO REMOTO (SEU CÓDIGO)
      - name: Start Remote Desktop
        run: |
          $env:PROGRAMFILES_X86 = ${env:ProgramFiles(x86)}

          & "$env:PROGRAMFILES_X86\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" `
          --code="4/0Aci98E-02dXYrsucisYGiurKWR64B3r6nic8OUVG5ZjmJyLJobIsbKOHYZbZPd5nLNS1hg" `
          --redirect-url="https://remotedesktop.google.com/_/oauthredirect" `
          --name=$env:COMPUTERNAME

      # ⏱️ MANTER ONLINE
      - name: Keep Alive
        run: |
          Write-Host "PC online..."
          Start-Sleep -Seconds 21600
